### ISSUE TITLE
[BUG] indices.put_settings::query.ignore_unavailable param description is wrong.

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-api-specification#243]
### What is the bug?
indices.put_settings::query.ignore_unavailable param description is wrong.

### How can one reproduce the bug?

From spec: https://github.com/opensearch-project/opensearch-api-specification/releases/download/main/opensearch-openapi.yaml

- `indices.put_settings::query.ignore_unavailable` param description is wrong. It is given description of other param `indices.put_settings::query.flat_settings`

  ```
  indices.put_settings::query.flat_settings:
      in: query
      name: flat_settings
      description: If `true`, returns settings in flat format.
      schema:
        type: boolean
      style: form


```
 indices.put_settings::query.ignore_unavailable:
      in: query
      name: ignore_unavailable
      description: If `true`, returns settings in flat format.
      schema:
        type: boolean
      style: form
```
