### ISSUE TITLE
[BUG]Remove default values present in parameter descriptions. 

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-api-specification#263]
### What is the bug?
Remove default values present in parameter descriptions as they are present in schema[default]. 

### How can one reproduce the bug?
example:

   ```
 cluster.put_settings::query.flat_settings:
      in: query
      name: flat_settings
      description: 'Return settings in flat format (default: false)'
      schema:
        type: boolean
        default: false
      style: form

```
