### ISSUE TITLE
[FEATURE] Add support for flags (parameters without value)

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#361]
### Is your feature request related to a problem?

The `_cat` API takes flags in the form of `?help` without a value. Currently these can't be expressed.

```
  - synopsis: Cat displaying all available headers (help).
    method: GET
    path: /_cat/health
    parameters:
      help: null
    response:
      status: 200
      content_type: text/plain
```

### What solution would you like?

Not sure. 

### Do you have any additional context?

This was discussed in https://github.com/OAI/OpenAPI-Specification/issues/1782.
