### ISSUE TITLE
[FEATURE] Failing story validation does not tell which property is unevaluated

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#364]
### Is your feature request related to a problem?

After #362 if a story has an unevaluated property the error doesn't say which property is unevaluated.

In the following example `synopsis` is invalid.

```
prologues:
  - synopsis: Create an index named `books` with mappings and settings.
    path: /{index}
    method: PUT
    parameters:
      index: books
    request_body:
      payload: {}
```

When running tests.

```
ERROR   cat/indices.yaml (Invalid Story: data/prologues/0 must NOT have unevaluated properties)
```

### What solution would you like?

Similar to the use of `ajv_errors` in the response body/schema validator.
