### ISSUE TITLE
[BUG] Response content-type in spec tests is not validated

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#392]
### What is the bug?

Coming from https://github.com/opensearch-project/opensearch-api-specification/pull/386#discussion_r1671365618, looks like `response/content-type` is not validated.

### How can one reproduce the bug?

In tests.

```yaml
    response:
      status: 200
      content_type: x/z // doesn't matter what you put here
```

### What is the expected behavior?

Fail if the response type is incorrect.
