### ISSUE TITLE
[FEATURE] Add support for passing headers when writing tests

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/opensearch-api-specification#438]
### Is your feature request related to a problem?
This feature requests modification of the test framework currently implemented to allow usage of headers when writing tests. This would allow for usage of credentials other than admin when writing tests. This would grant more flexibility especially for security related APIs.

### What solution would you like?
- ability to use credentials other than admin when writing tests for APIs.
```yaml
  - synopsis: Change password.
    path: /_plugins/_security/api/account
    method: PUT
    headers:
      authorization: "Basic <base64-encoded-string>"   <----
    request_body:
      payload:
        current_password: "myWeakPassword123!"
        password: "myStrongPassword123!"
    response:
      status: 200
```
