### ISSUE TITLE
[BUG][Test Framework] `response.payload` is set always set to null for non-2XX responses

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#482]
Consider this 403 response:
```yaml
    security.delete_distinguished_name@403:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                enum:
                  - 403
                  - FORBIDDEN
              message:
                type: string
                description: Message returned as part of Forbidden response.
```
When a 403 happens to a `security.delete_distinguished_name` request, the cluster also returns a response body with `{"status":"FORBIDDEN","message":"Access denied"}`. However testing this in a test story will result in this error when validating the response body:
```
[INFO] * undefined
[INFO] & "data must be object, data must be object"
```
That is the test framework thought the returned payload was null. This is a bug in the framework and most likely caused by this [line](https://github.com/opensearch-project/opensearch-api-specification/blob/main/tools/src/tester/ChapterReader.ts#L64):
```ts
if (payload !== undefined) response.payload = payload.error
```
The `response.payload` is set to `payload.error` while the payload itself is `{"status":"FORBIDDEN","message":"Access denied"}`, resulting in `response.payload = undefined`
