### ISSUE TITLE
[FEATURE] Add support for custom authorization headers in chapters section of the tests.

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/opensearch-api-specification#485]
### Is your feature request related to a problem?
As of now, there are two ways http_client sets the authorization (see [here](https://github.com/opensearch-project/opensearch-api-specification/blob/main/tools/src/tester/test.ts#L67)):
1. Default username and password (admin and myStrongPassword123!)
2. A username and password supplied through CLI (process.env.OPENSEARCH_USERNAME and process.env.OPENSEARCH_PASSWORD)

This will apply to all tests and there is no option to apply it to a specific chapter or test file.

### What solution would you like?
This issue requests addition of another way of passing custom authorization headers in `request` block of chapters. This will then be used by http_client to execute requests. It should look something like this:
```yaml
  - synopsis: ...
    path: ...
    method: ...
    request:
      headers:
        authorization: Basic <base64-encoded-creds>
      payload:
        ...
    response:
      ...
```

### What alternatives have you considered?
NA

### Do you have any additional context?
- https://github.com/opensearch-project/opensearch-api-specification/blob/main/tools/tests/tester/helpers.ts#L45
- https://github.com/opensearch-project/opensearch-api-specification/pull/439#discussion_r1711800406
