### ISSUE TITLE
[FEATURE][Spec Linter] Enforce `string or string[]` for comma-seperated  path params

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#514]
Many OpenSearch path params accept an array of values in the form of `comma-separated list of values`. This can be represented as a string or an array:
```yaml
schema:
  anyOf:
    - type: string
    - type: array
       items:
         type: string
```

However, many of of such path params in our spec are described as one of the two, but not both. To enforce this, we should looke for 1 of the following:
- If a path param is described as an array only, it should throw an error because that path param will also accept a comma-separated string equivalence.
- If the description of the path param mentions `comma separated` or `comma deliminated` (with or without hyphen), we must also enforce `string | string[]` schema.
