### ISSUE TITLE
[FEATURE] Represent enums which have aliases

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-api-specification#593]
### Is your feature request related to a problem?
There are enums that OpenSearch accepts where multiple string representations map to the same value, with one being the canonical representation (i.e. they're aliased).

Example:
Current spec of [`GeoOrientation`](https://github.com/opensearch-project/opensearch-api-specification/blob/main/spec/schemas/_common.mapping.yaml#L926):
```yaml
GeoOrientation:
      type: string
      enum:
        - left
        - right
```

Implementation of [`Orientation`](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/geo/builders/ShapeBuilder.java#L429) in OpenSearch:
```java
public static Orientation fromString(String orientation) {
            orientation = orientation.toLowerCase(Locale.ROOT);
            switch (orientation) {
                case "right":
                case "counterclockwise":
                case "ccw":
                    return Orientation.RIGHT;
                case "left":
                case "clockwise":
                case "cw":
                    return Orientation.LEFT;
                default:
                    throw new IllegalArgumentException("Unknown orientation [" + orientation + "]");
            }
        }
```

Existing implementation of [`GeoOrientation`](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/_types/mapping/GeoOrientation.java) in opensearch-java (on serialization first item is used, all accepted for deserialization):
```java
public enum GeoOrientation implements JsonEnum {
    Right("right", "RIGHT", "counterclockwise", "ccw"),

    Left("left", "LEFT", "clockwise", "cw");
}
```
Note that we also handle all-caps variants as if OpenSearch itself sets and returns its version it will be uppercase.

This means the final spec should be roughly equivalent to:
```yaml
GeoOrientation:
      type: string
      enum:
        - left
        - LEFT
        - clockwise
        - cw
        - right
        - RIGHT
        - counterclockwise
        - ccw
```
But should also communicate that `left` and `right` are the canonical versions and others map onto them.

**Comment by Xtansia** [comment]
What are your thoughts @dblock @nhtruong?

**Comment by Xtansia** [comment]
We could potentially re-use the `oneOf` concept like was used for [deprecated enums](https://github.com/opensearch-project/opensearch-api-specification/blob/main/spec/schemas/_common.yaml#L1941) and combine it with the `title` property:

```yaml
GeoOrientation:
  oneOf:
    - title: left
      type: string
      enum:
        - left
        - LEFT
        - clockwise
        - cw
    - title: right
      type: string
      enum:
        - right
        - RIGHT
        - counterclockwise
        - ccw
```
