### ISSUE TITLE
[BUG] Schema validation fails to prevent invalid 'until' property in retry configuration

### ISSUE THREAD

**Issue by nathaliellenaa** [opensearch-project/opensearch-api-specification#757]
### What is the bug?
The schema validation is not preventing the use of an invalid `until` property in the `retry` configuration.

### How can one reproduce the bug?
```
retry:
  count: 3
  wait: 10000
  until:
    - path: payload.state
      equal: COMPLETED
```
No error is thrown, despite `until` not being a valid property in the `retry` [schema](https://github.com/opensearch-project/opensearch-api-specification/blob/main/json_schemas/test_story.schema.yaml#L155).
### What is the expected behavior?
The schema validation should reject the configuration and throw an error, indicating that `until` is not a valid property in the `retry` configuration.
